name: Test and Build Static Website - Workflow

on:
  workflow_dispatch:

env:
  build-artifact: public-${{github.sha}}

jobs:
  setup-node-and-install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Calculate Cache Key
        id: cache-key
        run: |
          echo "CACHE_KEY=${{hashFiles('./node_modules/package-lock.json')}}"

      - name: Cache Dependencies
        uses: actions/cache@v4
        id: cache
        with:
          key: ${{steps.cache-key.outputs.CACHE_KEY}}
          #   key: CACHE_KEY=${{hashFiles('./node_modules/package-lock.json')}}
          path: ./node_modules

      - name: Install Dependencies
        if: ${{steps.cache.outputs.cache-hit != 'true'}}
        run: npm ci

  #   test-website:
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Test Website
  #         run: gatsby test

  build-website:
    runs-on: ubuntu-latest
    needs: setup-node-and-install-deps
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Gatsby-cli
        run: npm install -g gatsby-cli

      - name: Build Website
        run: gatsby build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./public
          name: ${{env.build-artifact}}
